on:
  push:
#  tags:
#    - "v*"

name: Create Release

jobs:
  build:
    name: Build Solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: get-solution-file-name
        name: Get solution file name
        run: |
          $xml = New-Object xml
          $xml.Load("./solution/Other/Solution.xml")
          $versionNode = $xml.SelectSingleNode("/ImportExportXml/SolutionManifest/Version")
          $version = $versionNode.InnerText
          $underscoredVersion = $version.Replace(".", "_")
          $fileName = "PowerAutomateExtendedTriggers_$underscoredVersion.zip"
          Write-Host "Solution file name: $fileName"
          Write-Host "::set-output name=name::$fileName"
        shell: pwsh
      - env:
          BASE: ${{ github.workspace }}
          ZIP_FILE: ${{ steps.get-solution-file-name.outputs.name }}
        name: Pack solution
        run: >
          npx pac-wrap solution pack
            --zipfile $ZIP_FILE
            --folder solution
            --packagetype Both
            --map map.xml
